env:
  DIR_BIN: "bin"
steps:

- command:
    - "$${DIR_BIN}/format.sh"
  label: ":gnu: format"
  agents:
    docker: "true"

- command:
    - "$${DIR_BIN}/build.sh"
  label: ":gnu: build"
  artifact_paths:
    - "build/main"
  agents:
    docker: "true"

- command:
    - "$${DIR_BIN}/build_avr.sh"
  label: ":gnu: build_avr"
  artifact_paths:
    - "build/main.elf"
    - "build/main.hex"
  agents:
    docker: "true"

- command:
    - "$${DIR_BIN}/docs_build.sh"
  label: ":md: docs build"
  artifact_paths:
    - "docs/html/**/*"
  agents:
    docker: "true"

- wait

- command:
    - "buildkite-agent artifact download docs/html/* ."
    - "$${DIR_BIN}/docs_deploy.sh"
  label: ":nginx: docs publish"
  branches: "master"
  agents:
    docker: "true"
